# Generated by Django 4.2.6 on 2023-11-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='kapybara', max_length=250, verbose_name='Sex')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('user_id', models.IntegerField(verbose_name='User_id')),
                ('login', models.CharField(max_length=250, verbose_name='login')),
                ('password', models.CharField(max_length=250, verbose_name='password')),
            ],
        ),
    ]
