# Generated by Django 4.2.6 on 2024-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=250, verbose_name='User_id'),
        ),
    ]
