# Generated by Django 4.2.6 on 2023-11-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='image_l',
            field=models.ImageField(default='E:/Books-Recommendation-System/webApp/main/static/main/img/kapibara.jpg', upload_to='', verbose_name='image_l'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_m',
            field=models.ImageField(default='E:/Books-Recommendation-System/webApp/main/static/main/img/kapibara.jpg', upload_to='', verbose_name='image_m'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_s',
            field=models.ImageField(default='E:/Books-Recommendation-System/webApp/main/static/main/img/kapibara.jpg', upload_to='', verbose_name='image_s'),
        ),
    ]
