# Generated by Django 4.2.6 on 2024-03-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_user_user_id_remove_userbook_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='default', max_length=250, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='user_id',
            field=models.CharField(default='default', max_length=250, verbose_name='Username'),
        ),
    ]
