# Generated by Django 4.2.6 on 2024-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_user_username_remove_userbook_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
    ]
